# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Yakumo_Koishi\repos\th07-reallyportable

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Yakumo_Koishi\repos\th07-reallyportable\build-web

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	"C:\Program Files\CMake\bin\cpack.exe" --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	"C:\Program Files\CMake\bin\cpack.exe" --config ./CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"headers\" \"pkgconfig\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Yakumo_Koishi\repos\th07-reallyportable\build-web\CMakeFiles C:\Users\Yakumo_Koishi\repos\th07-reallyportable\build-web\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Yakumo_Koishi\repos\th07-reallyportable\build-web\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P C:\Users\Yakumo_Koishi\repos\th07-reallyportable\build-web\CMakeFiles\VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named th07

# Build rule for target.
th07: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 th07
.PHONY : th07

# fast build rule for target.
th07/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/build
.PHONY : th07/fast

#=============================================================================
# Target rules for targets named extract_bgm

# Build rule for target.
extract_bgm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 extract_bgm
.PHONY : extract_bgm

# fast build rule for target.
extract_bgm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\extract_bgm.dir\build.make CMakeFiles/extract_bgm.dir/build
.PHONY : extract_bgm/fast

#=============================================================================
# Target rules for targets named SDL3-static

# Build rule for target.
SDL3-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 SDL3-static
.PHONY : SDL3-static

# fast build rule for target.
SDL3-static/fast:
	$(MAKE) $(MAKESILENT) -f vendored\SDL\CMakeFiles\SDL3-static.dir\build.make vendored/SDL/CMakeFiles/SDL3-static.dir/build
.PHONY : SDL3-static/fast

#=============================================================================
# Target rules for targets named SDL3_test

# Build rule for target.
SDL3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 SDL3_test
.PHONY : SDL3_test

# fast build rule for target.
SDL3_test/fast:
	$(MAKE) $(MAKESILENT) -f vendored\SDL\CMakeFiles\SDL3_test.dir\build.make vendored/SDL/CMakeFiles/SDL3_test.dir/build
.PHONY : SDL3_test/fast

#=============================================================================
# Target rules for targets named SDL3_image-static

# Build rule for target.
SDL3_image-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 SDL3_image-static
.PHONY : SDL3_image-static

# fast build rule for target.
SDL3_image-static/fast:
	$(MAKE) $(MAKESILENT) -f vendored\SDL_image\CMakeFiles\SDL3_image-static.dir\build.make vendored/SDL_image/CMakeFiles/SDL3_image-static.dir/build
.PHONY : SDL3_image-static/fast

#=============================================================================
# Target rules for targets named SDL3_ttf-static

# Build rule for target.
SDL3_ttf-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 SDL3_ttf-static
.PHONY : SDL3_ttf-static

# fast build rule for target.
SDL3_ttf-static/fast:
	$(MAKE) $(MAKESILENT) -f vendored\SDL_ttf\CMakeFiles\SDL3_ttf-static.dir\build.make vendored/SDL_ttf/CMakeFiles/SDL3_ttf-static.dir/build
.PHONY : SDL3_ttf-static/fast

#=============================================================================
# Target rules for targets named freetype

# Build rule for target.
freetype: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 freetype
.PHONY : freetype

# fast build rule for target.
freetype/fast:
	$(MAKE) $(MAKESILENT) -f vendored\SDL_ttf\external\freetype\CMakeFiles\freetype.dir\build.make vendored/SDL_ttf/external/freetype/CMakeFiles/freetype.dir/build
.PHONY : freetype/fast

#=============================================================================
# Target rules for targets named plutovg

# Build rule for target.
plutovg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 plutovg
.PHONY : plutovg

# fast build rule for target.
plutovg/fast:
	$(MAKE) $(MAKESILENT) -f vendored\SDL_ttf\external\plutovg\CMakeFiles\plutovg.dir\build.make vendored/SDL_ttf/external/plutovg/CMakeFiles/plutovg.dir/build
.PHONY : plutovg/fast

#=============================================================================
# Target rules for targets named plutosvg

# Build rule for target.
plutosvg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 plutosvg
.PHONY : plutosvg

# fast build rule for target.
plutosvg/fast:
	$(MAKE) $(MAKESILENT) -f vendored\SDL_ttf\external\plutosvg\CMakeFiles\plutosvg.dir\build.make vendored/SDL_ttf/external/plutosvg/CMakeFiles/plutosvg.dir/build
.PHONY : plutosvg/fast

src/AnmManager.o: src/AnmManager.cpp.o
.PHONY : src/AnmManager.o

# target to build an object file
src/AnmManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/AnmManager.cpp.o
.PHONY : src/AnmManager.cpp.o

src/AnmManager.i: src/AnmManager.cpp.i
.PHONY : src/AnmManager.i

# target to preprocess a source file
src/AnmManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/AnmManager.cpp.i
.PHONY : src/AnmManager.cpp.i

src/AnmManager.s: src/AnmManager.cpp.s
.PHONY : src/AnmManager.s

# target to generate assembly for a file
src/AnmManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/AnmManager.cpp.s
.PHONY : src/AnmManager.cpp.s

src/AnmVm.o: src/AnmVm.cpp.o
.PHONY : src/AnmVm.o

# target to build an object file
src/AnmVm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/AnmVm.cpp.o
.PHONY : src/AnmVm.cpp.o

src/AnmVm.i: src/AnmVm.cpp.i
.PHONY : src/AnmVm.i

# target to preprocess a source file
src/AnmVm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/AnmVm.cpp.i
.PHONY : src/AnmVm.cpp.i

src/AnmVm.s: src/AnmVm.cpp.s
.PHONY : src/AnmVm.s

# target to generate assembly for a file
src/AnmVm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/AnmVm.cpp.s
.PHONY : src/AnmVm.cpp.s

src/AsciiManager.o: src/AsciiManager.cpp.o
.PHONY : src/AsciiManager.o

# target to build an object file
src/AsciiManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/AsciiManager.cpp.o
.PHONY : src/AsciiManager.cpp.o

src/AsciiManager.i: src/AsciiManager.cpp.i
.PHONY : src/AsciiManager.i

# target to preprocess a source file
src/AsciiManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/AsciiManager.cpp.i
.PHONY : src/AsciiManager.cpp.i

src/AsciiManager.s: src/AsciiManager.cpp.s
.PHONY : src/AsciiManager.s

# target to generate assembly for a file
src/AsciiManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/AsciiManager.cpp.s
.PHONY : src/AsciiManager.cpp.s

src/BombData.o: src/BombData.cpp.o
.PHONY : src/BombData.o

# target to build an object file
src/BombData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/BombData.cpp.o
.PHONY : src/BombData.cpp.o

src/BombData.i: src/BombData.cpp.i
.PHONY : src/BombData.i

# target to preprocess a source file
src/BombData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/BombData.cpp.i
.PHONY : src/BombData.cpp.i

src/BombData.s: src/BombData.cpp.s
.PHONY : src/BombData.s

# target to generate assembly for a file
src/BombData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/BombData.cpp.s
.PHONY : src/BombData.cpp.s

src/BulletManager.o: src/BulletManager.cpp.o
.PHONY : src/BulletManager.o

# target to build an object file
src/BulletManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/BulletManager.cpp.o
.PHONY : src/BulletManager.cpp.o

src/BulletManager.i: src/BulletManager.cpp.i
.PHONY : src/BulletManager.i

# target to preprocess a source file
src/BulletManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/BulletManager.cpp.i
.PHONY : src/BulletManager.cpp.i

src/BulletManager.s: src/BulletManager.cpp.s
.PHONY : src/BulletManager.s

# target to generate assembly for a file
src/BulletManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/BulletManager.cpp.s
.PHONY : src/BulletManager.cpp.s

src/Chain.o: src/Chain.cpp.o
.PHONY : src/Chain.o

# target to build an object file
src/Chain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Chain.cpp.o
.PHONY : src/Chain.cpp.o

src/Chain.i: src/Chain.cpp.i
.PHONY : src/Chain.i

# target to preprocess a source file
src/Chain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Chain.cpp.i
.PHONY : src/Chain.cpp.i

src/Chain.s: src/Chain.cpp.s
.PHONY : src/Chain.s

# target to generate assembly for a file
src/Chain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Chain.cpp.s
.PHONY : src/Chain.cpp.s

src/Controller.o: src/Controller.cpp.o
.PHONY : src/Controller.o

# target to build an object file
src/Controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Controller.cpp.o
.PHONY : src/Controller.cpp.o

src/Controller.i: src/Controller.cpp.i
.PHONY : src/Controller.i

# target to preprocess a source file
src/Controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Controller.cpp.i
.PHONY : src/Controller.cpp.i

src/Controller.s: src/Controller.cpp.s
.PHONY : src/Controller.s

# target to generate assembly for a file
src/Controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Controller.cpp.s
.PHONY : src/Controller.cpp.s

src/EclManager.o: src/EclManager.cpp.o
.PHONY : src/EclManager.o

# target to build an object file
src/EclManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/EclManager.cpp.o
.PHONY : src/EclManager.cpp.o

src/EclManager.i: src/EclManager.cpp.i
.PHONY : src/EclManager.i

# target to preprocess a source file
src/EclManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/EclManager.cpp.i
.PHONY : src/EclManager.cpp.i

src/EclManager.s: src/EclManager.cpp.s
.PHONY : src/EclManager.s

# target to generate assembly for a file
src/EclManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/EclManager.cpp.s
.PHONY : src/EclManager.cpp.s

src/EffectManager.o: src/EffectManager.cpp.o
.PHONY : src/EffectManager.o

# target to build an object file
src/EffectManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/EffectManager.cpp.o
.PHONY : src/EffectManager.cpp.o

src/EffectManager.i: src/EffectManager.cpp.i
.PHONY : src/EffectManager.i

# target to preprocess a source file
src/EffectManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/EffectManager.cpp.i
.PHONY : src/EffectManager.cpp.i

src/EffectManager.s: src/EffectManager.cpp.s
.PHONY : src/EffectManager.s

# target to generate assembly for a file
src/EffectManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/EffectManager.cpp.s
.PHONY : src/EffectManager.cpp.s

src/Ending.o: src/Ending.cpp.o
.PHONY : src/Ending.o

# target to build an object file
src/Ending.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Ending.cpp.o
.PHONY : src/Ending.cpp.o

src/Ending.i: src/Ending.cpp.i
.PHONY : src/Ending.i

# target to preprocess a source file
src/Ending.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Ending.cpp.i
.PHONY : src/Ending.cpp.i

src/Ending.s: src/Ending.cpp.s
.PHONY : src/Ending.s

# target to generate assembly for a file
src/Ending.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Ending.cpp.s
.PHONY : src/Ending.cpp.s

src/EnemyEclInstr.o: src/EnemyEclInstr.cpp.o
.PHONY : src/EnemyEclInstr.o

# target to build an object file
src/EnemyEclInstr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/EnemyEclInstr.cpp.o
.PHONY : src/EnemyEclInstr.cpp.o

src/EnemyEclInstr.i: src/EnemyEclInstr.cpp.i
.PHONY : src/EnemyEclInstr.i

# target to preprocess a source file
src/EnemyEclInstr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/EnemyEclInstr.cpp.i
.PHONY : src/EnemyEclInstr.cpp.i

src/EnemyEclInstr.s: src/EnemyEclInstr.cpp.s
.PHONY : src/EnemyEclInstr.s

# target to generate assembly for a file
src/EnemyEclInstr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/EnemyEclInstr.cpp.s
.PHONY : src/EnemyEclInstr.cpp.s

src/EnemyManager.o: src/EnemyManager.cpp.o
.PHONY : src/EnemyManager.o

# target to build an object file
src/EnemyManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/EnemyManager.cpp.o
.PHONY : src/EnemyManager.cpp.o

src/EnemyManager.i: src/EnemyManager.cpp.i
.PHONY : src/EnemyManager.i

# target to preprocess a source file
src/EnemyManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/EnemyManager.cpp.i
.PHONY : src/EnemyManager.cpp.i

src/EnemyManager.s: src/EnemyManager.cpp.s
.PHONY : src/EnemyManager.s

# target to generate assembly for a file
src/EnemyManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/EnemyManager.cpp.s
.PHONY : src/EnemyManager.cpp.s

src/FileSystem.o: src/FileSystem.cpp.o
.PHONY : src/FileSystem.o

# target to build an object file
src/FileSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/FileSystem.cpp.o
.PHONY : src/FileSystem.cpp.o

src/FileSystem.i: src/FileSystem.cpp.i
.PHONY : src/FileSystem.i

# target to preprocess a source file
src/FileSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/FileSystem.cpp.i
.PHONY : src/FileSystem.cpp.i

src/FileSystem.s: src/FileSystem.cpp.s
.PHONY : src/FileSystem.s

# target to generate assembly for a file
src/FileSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/FileSystem.cpp.s
.PHONY : src/FileSystem.cpp.s

src/GameErrorContext.o: src/GameErrorContext.cpp.o
.PHONY : src/GameErrorContext.o

# target to build an object file
src/GameErrorContext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/GameErrorContext.cpp.o
.PHONY : src/GameErrorContext.cpp.o

src/GameErrorContext.i: src/GameErrorContext.cpp.i
.PHONY : src/GameErrorContext.i

# target to preprocess a source file
src/GameErrorContext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/GameErrorContext.cpp.i
.PHONY : src/GameErrorContext.cpp.i

src/GameErrorContext.s: src/GameErrorContext.cpp.s
.PHONY : src/GameErrorContext.s

# target to generate assembly for a file
src/GameErrorContext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/GameErrorContext.cpp.s
.PHONY : src/GameErrorContext.cpp.s

src/GameManager.o: src/GameManager.cpp.o
.PHONY : src/GameManager.o

# target to build an object file
src/GameManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/GameManager.cpp.o
.PHONY : src/GameManager.cpp.o

src/GameManager.i: src/GameManager.cpp.i
.PHONY : src/GameManager.i

# target to preprocess a source file
src/GameManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/GameManager.cpp.i
.PHONY : src/GameManager.cpp.i

src/GameManager.s: src/GameManager.cpp.s
.PHONY : src/GameManager.s

# target to generate assembly for a file
src/GameManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/GameManager.cpp.s
.PHONY : src/GameManager.cpp.s

src/GameWindow.o: src/GameWindow.cpp.o
.PHONY : src/GameWindow.o

# target to build an object file
src/GameWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/GameWindow.cpp.o
.PHONY : src/GameWindow.cpp.o

src/GameWindow.i: src/GameWindow.cpp.i
.PHONY : src/GameWindow.i

# target to preprocess a source file
src/GameWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/GameWindow.cpp.i
.PHONY : src/GameWindow.cpp.i

src/GameWindow.s: src/GameWindow.cpp.s
.PHONY : src/GameWindow.s

# target to generate assembly for a file
src/GameWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/GameWindow.cpp.s
.PHONY : src/GameWindow.cpp.s

src/Gui.o: src/Gui.cpp.o
.PHONY : src/Gui.o

# target to build an object file
src/Gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Gui.cpp.o
.PHONY : src/Gui.cpp.o

src/Gui.i: src/Gui.cpp.i
.PHONY : src/Gui.i

# target to preprocess a source file
src/Gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Gui.cpp.i
.PHONY : src/Gui.cpp.i

src/Gui.s: src/Gui.cpp.s
.PHONY : src/Gui.s

# target to generate assembly for a file
src/Gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Gui.cpp.s
.PHONY : src/Gui.cpp.s

src/ItemManager.o: src/ItemManager.cpp.o
.PHONY : src/ItemManager.o

# target to build an object file
src/ItemManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/ItemManager.cpp.o
.PHONY : src/ItemManager.cpp.o

src/ItemManager.i: src/ItemManager.cpp.i
.PHONY : src/ItemManager.i

# target to preprocess a source file
src/ItemManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/ItemManager.cpp.i
.PHONY : src/ItemManager.cpp.i

src/ItemManager.s: src/ItemManager.cpp.s
.PHONY : src/ItemManager.s

# target to generate assembly for a file
src/ItemManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/ItemManager.cpp.s
.PHONY : src/ItemManager.cpp.s

src/MainMenu.o: src/MainMenu.cpp.o
.PHONY : src/MainMenu.o

# target to build an object file
src/MainMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/MainMenu.cpp.o
.PHONY : src/MainMenu.cpp.o

src/MainMenu.i: src/MainMenu.cpp.i
.PHONY : src/MainMenu.i

# target to preprocess a source file
src/MainMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/MainMenu.cpp.i
.PHONY : src/MainMenu.cpp.i

src/MainMenu.s: src/MainMenu.cpp.s
.PHONY : src/MainMenu.s

# target to generate assembly for a file
src/MainMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/MainMenu.cpp.s
.PHONY : src/MainMenu.cpp.s

src/MidiOutput.o: src/MidiOutput.cpp.o
.PHONY : src/MidiOutput.o

# target to build an object file
src/MidiOutput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/MidiOutput.cpp.o
.PHONY : src/MidiOutput.cpp.o

src/MidiOutput.i: src/MidiOutput.cpp.i
.PHONY : src/MidiOutput.i

# target to preprocess a source file
src/MidiOutput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/MidiOutput.cpp.i
.PHONY : src/MidiOutput.cpp.i

src/MidiOutput.s: src/MidiOutput.cpp.s
.PHONY : src/MidiOutput.s

# target to generate assembly for a file
src/MidiOutput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/MidiOutput.cpp.s
.PHONY : src/MidiOutput.cpp.s

src/MusicRoom.o: src/MusicRoom.cpp.o
.PHONY : src/MusicRoom.o

# target to build an object file
src/MusicRoom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/MusicRoom.cpp.o
.PHONY : src/MusicRoom.cpp.o

src/MusicRoom.i: src/MusicRoom.cpp.i
.PHONY : src/MusicRoom.i

# target to preprocess a source file
src/MusicRoom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/MusicRoom.cpp.i
.PHONY : src/MusicRoom.cpp.i

src/MusicRoom.s: src/MusicRoom.cpp.s
.PHONY : src/MusicRoom.s

# target to generate assembly for a file
src/MusicRoom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/MusicRoom.cpp.s
.PHONY : src/MusicRoom.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/ReplayManager.o: src/ReplayManager.cpp.o
.PHONY : src/ReplayManager.o

# target to build an object file
src/ReplayManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/ReplayManager.cpp.o
.PHONY : src/ReplayManager.cpp.o

src/ReplayManager.i: src/ReplayManager.cpp.i
.PHONY : src/ReplayManager.i

# target to preprocess a source file
src/ReplayManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/ReplayManager.cpp.i
.PHONY : src/ReplayManager.cpp.i

src/ReplayManager.s: src/ReplayManager.cpp.s
.PHONY : src/ReplayManager.s

# target to generate assembly for a file
src/ReplayManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/ReplayManager.cpp.s
.PHONY : src/ReplayManager.cpp.s

src/ResultScreen.o: src/ResultScreen.cpp.o
.PHONY : src/ResultScreen.o

# target to build an object file
src/ResultScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/ResultScreen.cpp.o
.PHONY : src/ResultScreen.cpp.o

src/ResultScreen.i: src/ResultScreen.cpp.i
.PHONY : src/ResultScreen.i

# target to preprocess a source file
src/ResultScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/ResultScreen.cpp.i
.PHONY : src/ResultScreen.cpp.i

src/ResultScreen.s: src/ResultScreen.cpp.s
.PHONY : src/ResultScreen.s

# target to generate assembly for a file
src/ResultScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/ResultScreen.cpp.s
.PHONY : src/ResultScreen.cpp.s

src/Rng.o: src/Rng.cpp.o
.PHONY : src/Rng.o

# target to build an object file
src/Rng.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Rng.cpp.o
.PHONY : src/Rng.cpp.o

src/Rng.i: src/Rng.cpp.i
.PHONY : src/Rng.i

# target to preprocess a source file
src/Rng.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Rng.cpp.i
.PHONY : src/Rng.cpp.i

src/Rng.s: src/Rng.cpp.s
.PHONY : src/Rng.s

# target to generate assembly for a file
src/Rng.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Rng.cpp.s
.PHONY : src/Rng.cpp.s

src/ScreenEffect.o: src/ScreenEffect.cpp.o
.PHONY : src/ScreenEffect.o

# target to build an object file
src/ScreenEffect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/ScreenEffect.cpp.o
.PHONY : src/ScreenEffect.cpp.o

src/ScreenEffect.i: src/ScreenEffect.cpp.i
.PHONY : src/ScreenEffect.i

# target to preprocess a source file
src/ScreenEffect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/ScreenEffect.cpp.i
.PHONY : src/ScreenEffect.cpp.i

src/ScreenEffect.s: src/ScreenEffect.cpp.s
.PHONY : src/ScreenEffect.s

# target to generate assembly for a file
src/ScreenEffect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/ScreenEffect.cpp.s
.PHONY : src/ScreenEffect.cpp.s

src/SoundPlayer.o: src/SoundPlayer.cpp.o
.PHONY : src/SoundPlayer.o

# target to build an object file
src/SoundPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/SoundPlayer.cpp.o
.PHONY : src/SoundPlayer.cpp.o

src/SoundPlayer.i: src/SoundPlayer.cpp.i
.PHONY : src/SoundPlayer.i

# target to preprocess a source file
src/SoundPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/SoundPlayer.cpp.i
.PHONY : src/SoundPlayer.cpp.i

src/SoundPlayer.s: src/SoundPlayer.cpp.s
.PHONY : src/SoundPlayer.s

# target to generate assembly for a file
src/SoundPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/SoundPlayer.cpp.s
.PHONY : src/SoundPlayer.cpp.s

src/Stage.o: src/Stage.cpp.o
.PHONY : src/Stage.o

# target to build an object file
src/Stage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Stage.cpp.o
.PHONY : src/Stage.cpp.o

src/Stage.i: src/Stage.cpp.i
.PHONY : src/Stage.i

# target to preprocess a source file
src/Stage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Stage.cpp.i
.PHONY : src/Stage.cpp.i

src/Stage.s: src/Stage.cpp.s
.PHONY : src/Stage.s

# target to generate assembly for a file
src/Stage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Stage.cpp.s
.PHONY : src/Stage.cpp.s

src/Supervisor.o: src/Supervisor.cpp.o
.PHONY : src/Supervisor.o

# target to build an object file
src/Supervisor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Supervisor.cpp.o
.PHONY : src/Supervisor.cpp.o

src/Supervisor.i: src/Supervisor.cpp.i
.PHONY : src/Supervisor.i

# target to preprocess a source file
src/Supervisor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Supervisor.cpp.i
.PHONY : src/Supervisor.cpp.i

src/Supervisor.s: src/Supervisor.cpp.s
.PHONY : src/Supervisor.s

# target to generate assembly for a file
src/Supervisor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Supervisor.cpp.s
.PHONY : src/Supervisor.cpp.s

src/TextHelper.o: src/TextHelper.cpp.o
.PHONY : src/TextHelper.o

# target to build an object file
src/TextHelper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/TextHelper.cpp.o
.PHONY : src/TextHelper.cpp.o

src/TextHelper.i: src/TextHelper.cpp.i
.PHONY : src/TextHelper.i

# target to preprocess a source file
src/TextHelper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/TextHelper.cpp.i
.PHONY : src/TextHelper.cpp.i

src/TextHelper.s: src/TextHelper.cpp.s
.PHONY : src/TextHelper.s

# target to generate assembly for a file
src/TextHelper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/TextHelper.cpp.s
.PHONY : src/TextHelper.cpp.s

src/Touch.o: src/Touch.cpp.o
.PHONY : src/Touch.o

# target to build an object file
src/Touch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Touch.cpp.o
.PHONY : src/Touch.cpp.o

src/Touch.i: src/Touch.cpp.i
.PHONY : src/Touch.i

# target to preprocess a source file
src/Touch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Touch.cpp.i
.PHONY : src/Touch.cpp.i

src/Touch.s: src/Touch.cpp.s
.PHONY : src/Touch.s

# target to generate assembly for a file
src/Touch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/Touch.cpp.s
.PHONY : src/Touch.cpp.s

src/graphics/Gles.o: src/graphics/Gles.cpp.o
.PHONY : src/graphics/Gles.o

# target to build an object file
src/graphics/Gles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/graphics/Gles.cpp.o
.PHONY : src/graphics/Gles.cpp.o

src/graphics/Gles.i: src/graphics/Gles.cpp.i
.PHONY : src/graphics/Gles.i

# target to preprocess a source file
src/graphics/Gles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/graphics/Gles.cpp.i
.PHONY : src/graphics/Gles.cpp.i

src/graphics/Gles.s: src/graphics/Gles.cpp.s
.PHONY : src/graphics/Gles.s

# target to generate assembly for a file
src/graphics/Gles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/graphics/Gles.cpp.s
.PHONY : src/graphics/Gles.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pbg4/Lzss.o: src/pbg4/Lzss.cpp.o
.PHONY : src/pbg4/Lzss.o

# target to build an object file
src/pbg4/Lzss.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/pbg4/Lzss.cpp.o
.PHONY : src/pbg4/Lzss.cpp.o

src/pbg4/Lzss.i: src/pbg4/Lzss.cpp.i
.PHONY : src/pbg4/Lzss.i

# target to preprocess a source file
src/pbg4/Lzss.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/pbg4/Lzss.cpp.i
.PHONY : src/pbg4/Lzss.cpp.i

src/pbg4/Lzss.s: src/pbg4/Lzss.cpp.s
.PHONY : src/pbg4/Lzss.s

# target to generate assembly for a file
src/pbg4/Lzss.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/pbg4/Lzss.cpp.s
.PHONY : src/pbg4/Lzss.cpp.s

src/pbg4/Pbg4Archive.o: src/pbg4/Pbg4Archive.cpp.o
.PHONY : src/pbg4/Pbg4Archive.o

# target to build an object file
src/pbg4/Pbg4Archive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/pbg4/Pbg4Archive.cpp.o
.PHONY : src/pbg4/Pbg4Archive.cpp.o

src/pbg4/Pbg4Archive.i: src/pbg4/Pbg4Archive.cpp.i
.PHONY : src/pbg4/Pbg4Archive.i

# target to preprocess a source file
src/pbg4/Pbg4Archive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/pbg4/Pbg4Archive.cpp.i
.PHONY : src/pbg4/Pbg4Archive.cpp.i

src/pbg4/Pbg4Archive.s: src/pbg4/Pbg4Archive.cpp.s
.PHONY : src/pbg4/Pbg4Archive.s

# target to generate assembly for a file
src/pbg4/Pbg4Archive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/pbg4/Pbg4Archive.cpp.s
.PHONY : src/pbg4/Pbg4Archive.cpp.s

src/pbg4/Pbg4File.o: src/pbg4/Pbg4File.cpp.o
.PHONY : src/pbg4/Pbg4File.o

# target to build an object file
src/pbg4/Pbg4File.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/pbg4/Pbg4File.cpp.o
.PHONY : src/pbg4/Pbg4File.cpp.o

src/pbg4/Pbg4File.i: src/pbg4/Pbg4File.cpp.i
.PHONY : src/pbg4/Pbg4File.i

# target to preprocess a source file
src/pbg4/Pbg4File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/pbg4/Pbg4File.cpp.i
.PHONY : src/pbg4/Pbg4File.cpp.i

src/pbg4/Pbg4File.s: src/pbg4/Pbg4File.cpp.s
.PHONY : src/pbg4/Pbg4File.s

# target to generate assembly for a file
src/pbg4/Pbg4File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/pbg4/Pbg4File.cpp.s
.PHONY : src/pbg4/Pbg4File.cpp.s

src/sj2utf8/sj2utf8.o: src/sj2utf8/sj2utf8.cpp.o
.PHONY : src/sj2utf8/sj2utf8.o

# target to build an object file
src/sj2utf8/sj2utf8.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/sj2utf8/sj2utf8.cpp.o
.PHONY : src/sj2utf8/sj2utf8.cpp.o

src/sj2utf8/sj2utf8.i: src/sj2utf8/sj2utf8.cpp.i
.PHONY : src/sj2utf8/sj2utf8.i

# target to preprocess a source file
src/sj2utf8/sj2utf8.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/sj2utf8/sj2utf8.cpp.i
.PHONY : src/sj2utf8/sj2utf8.cpp.i

src/sj2utf8/sj2utf8.s: src/sj2utf8/sj2utf8.cpp.s
.PHONY : src/sj2utf8/sj2utf8.s

# target to generate assembly for a file
src/sj2utf8/sj2utf8.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/sj2utf8/sj2utf8.cpp.s
.PHONY : src/sj2utf8/sj2utf8.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\th07.dir\build.make CMakeFiles/th07.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... package
	@echo ... package_source
	@echo ... rebuild_cache
	@echo ... extract_bgm
	@echo ... SDL3-static
	@echo ... SDL3_image-static
	@echo ... SDL3_test
	@echo ... SDL3_ttf-static
	@echo ... freetype
	@echo ... plutosvg
	@echo ... plutovg
	@echo ... th07
	@echo ... src/AnmManager.o
	@echo ... src/AnmManager.i
	@echo ... src/AnmManager.s
	@echo ... src/AnmVm.o
	@echo ... src/AnmVm.i
	@echo ... src/AnmVm.s
	@echo ... src/AsciiManager.o
	@echo ... src/AsciiManager.i
	@echo ... src/AsciiManager.s
	@echo ... src/BombData.o
	@echo ... src/BombData.i
	@echo ... src/BombData.s
	@echo ... src/BulletManager.o
	@echo ... src/BulletManager.i
	@echo ... src/BulletManager.s
	@echo ... src/Chain.o
	@echo ... src/Chain.i
	@echo ... src/Chain.s
	@echo ... src/Controller.o
	@echo ... src/Controller.i
	@echo ... src/Controller.s
	@echo ... src/EclManager.o
	@echo ... src/EclManager.i
	@echo ... src/EclManager.s
	@echo ... src/EffectManager.o
	@echo ... src/EffectManager.i
	@echo ... src/EffectManager.s
	@echo ... src/Ending.o
	@echo ... src/Ending.i
	@echo ... src/Ending.s
	@echo ... src/EnemyEclInstr.o
	@echo ... src/EnemyEclInstr.i
	@echo ... src/EnemyEclInstr.s
	@echo ... src/EnemyManager.o
	@echo ... src/EnemyManager.i
	@echo ... src/EnemyManager.s
	@echo ... src/FileSystem.o
	@echo ... src/FileSystem.i
	@echo ... src/FileSystem.s
	@echo ... src/GameErrorContext.o
	@echo ... src/GameErrorContext.i
	@echo ... src/GameErrorContext.s
	@echo ... src/GameManager.o
	@echo ... src/GameManager.i
	@echo ... src/GameManager.s
	@echo ... src/GameWindow.o
	@echo ... src/GameWindow.i
	@echo ... src/GameWindow.s
	@echo ... src/Gui.o
	@echo ... src/Gui.i
	@echo ... src/Gui.s
	@echo ... src/ItemManager.o
	@echo ... src/ItemManager.i
	@echo ... src/ItemManager.s
	@echo ... src/MainMenu.o
	@echo ... src/MainMenu.i
	@echo ... src/MainMenu.s
	@echo ... src/MidiOutput.o
	@echo ... src/MidiOutput.i
	@echo ... src/MidiOutput.s
	@echo ... src/MusicRoom.o
	@echo ... src/MusicRoom.i
	@echo ... src/MusicRoom.s
	@echo ... src/Player.o
	@echo ... src/Player.i
	@echo ... src/Player.s
	@echo ... src/ReplayManager.o
	@echo ... src/ReplayManager.i
	@echo ... src/ReplayManager.s
	@echo ... src/ResultScreen.o
	@echo ... src/ResultScreen.i
	@echo ... src/ResultScreen.s
	@echo ... src/Rng.o
	@echo ... src/Rng.i
	@echo ... src/Rng.s
	@echo ... src/ScreenEffect.o
	@echo ... src/ScreenEffect.i
	@echo ... src/ScreenEffect.s
	@echo ... src/SoundPlayer.o
	@echo ... src/SoundPlayer.i
	@echo ... src/SoundPlayer.s
	@echo ... src/Stage.o
	@echo ... src/Stage.i
	@echo ... src/Stage.s
	@echo ... src/Supervisor.o
	@echo ... src/Supervisor.i
	@echo ... src/Supervisor.s
	@echo ... src/TextHelper.o
	@echo ... src/TextHelper.i
	@echo ... src/TextHelper.s
	@echo ... src/Touch.o
	@echo ... src/Touch.i
	@echo ... src/Touch.s
	@echo ... src/graphics/Gles.o
	@echo ... src/graphics/Gles.i
	@echo ... src/graphics/Gles.s
	@echo ... src/main.o
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/pbg4/Lzss.o
	@echo ... src/pbg4/Lzss.i
	@echo ... src/pbg4/Lzss.s
	@echo ... src/pbg4/Pbg4Archive.o
	@echo ... src/pbg4/Pbg4Archive.i
	@echo ... src/pbg4/Pbg4Archive.s
	@echo ... src/pbg4/Pbg4File.o
	@echo ... src/pbg4/Pbg4File.i
	@echo ... src/pbg4/Pbg4File.s
	@echo ... src/sj2utf8/sj2utf8.o
	@echo ... src/sj2utf8/sj2utf8.i
	@echo ... src/sj2utf8/sj2utf8.s
	@echo ... src/utils.o
	@echo ... src/utils.i
	@echo ... src/utils.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P C:\Users\Yakumo_Koishi\repos\th07-reallyportable\build-web\CMakeFiles\VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

